# Generated by Django 6.0.3 on 2026-04-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='if_active',
            new_name='is_active',
        ),
    ]
